### PR TITLE
Update to ScummVM 1.9.0

### PR DESCRIPTION
**Pull request by RobLoach**
Bring the ScummVM core to [ScummVM 1.9.0](http://scummvm.org/news/20161017/) from https://github.com/libretro/scummvm/issues/48. @fetzerch made it happen.

1. Merge in the commits to update to 1.9.0
2. @fetzerch brought in [engine](https://github.com/fetzerch/scummvm/commit/77771243e4eb7b9d53ec76a3d5ec1fe88c92fd09) [fixes](https://github.com/fetzerch/scummvm/commit/64fd78194a8ab5a2da01fadcb4f86715310fb65e)
3. I recompiled and tested, working well

Side node: @fetzerch Is sound working for you?

### CODE REVIEW

**Comment by fetzerch** [comment]
Thx for testing, Audio is working fine here. No FLAC or MP3 still, but that's a different issue. Both libflac and libmad have to be compiled in statically.

**Comment by fetzerch** [comment]
FLAC & MP3 support added, the necessary dependencies were already there. That should fix https://github.com/libretro/scummvm/issues/12.

**Comment by RobLoach** [comment]
> FLAC & MP3 support added, the necessary dependencies were already there

That will probably fix the audio issues I had. Thanks!

**Comment by hericstrada** [comment]
Hi guys, sorry if this is not the place. I use Lakka and im needing a ScummVm core with flac support. How can I use this new update?   (im not a developer,  I dont know how to recompile those things)  Thanks for all the hard work!

**Comment by RobLoach** [comment]
@hericstrada Get Kiv to build a new Lakka ScummVM core :wink:

**Comment by hericstrada** [comment]
@RobLoach, thanks for the reply! I´ll be embarassed to ask you or Kivutar anything.^^ I don´t know if those nightly builds are generated from this master branch. If they are, I can get the core from there myself... If not, thanks anyway, I can wait till a new release. Amazing work all of you. LibRetro, Retroarch and Lakka made my year. xD

**Pull request merged**
