### PR TITLE
Add auxiliary data bundle

### PR DESCRIPTION
**Pull request by jdgleaver**
This pull request is slightly irregular, but I think it is justified...

ScummVM is unusual in that it requires a number of diverse auxiliary data files in order to function correctly. When using stand-alone ScummVM, most of these files are included in the installation/distribution package - but with RetroArch you only get the core binary and the user is left to fend for themselves. This can lead to suboptimal configurations and errors such as those in issue #93.

This pull request just bundles (almost all of) the required extra data into an easily accessible archive which the user can extract to their RetroArch system directory. I think the repository is a good place for this since (a) most of the files are already part of the repository and (b) hosting files on github means bandwidth isn't an issue. The archive (scummvm.zip) contains the following:

- All required engine data files

- The 'scummmodern' theme (the default black-and-green interface does not make for a pleasant user experience)

- A tiny yet authentic/high quality soundfont, required for MIDI emulation

A script is included to update the archive should any of the constituent files change. The only items not included are the MT-32 ROM files, which are legally ambiguous and cannot be distributed.

I intend to reference/explain the 'scummvm.zip' archive in a forthcoming documentation update.

A final note about the soundfont:

I would normally be wary of including third-party files in a project, but I can see no objection in this case. The soundfont itself is taken from the GZDoom repository (https://github.com/coelckers/gzdoom/blob/master/soundfont/gzdoom.sf2), which makes it licensed under the GPL v3. ScummVM is licensed under the GPL v2, but under Section 5 of the GNU General Public License v3.0, inclusion of this soundfont in the ScummVM repository constitutes an "aggregate". The soundfont can therefore maintain its GPL v3 status without affecting the licensing of ScummVM - so nothing is violated.

### CODE REVIEW

**Comment by NelsonRosenberg** [comment]
This is excellent work, thank you @jdgleaver. Now we should just make some kind of guide so users know that they should unzip the files in retroarch/system, open scummvm in retroarch and set the "theme" and the "extra" path to point to that folder. I'm not sure there is a more automatic way to go about that.

**Comment by jdgleaver** [comment]
You mean a guide like this...?  https://docs.libretro.com/library/scummvm/

:slightly_smiling_face: 

I agree it would be nice to automate the file handling process, but I think the current manual config isn't too onerous...

**Comment by NelsonRosenberg** [comment]
Well, do I feel like a fool! Completely missed that! =)

Thanks again for the excellent work!

**Comment by jdgleaver** [comment]
Thanks for the appreciation!

**Pull request merged**
