### PR TITLE
LIBRETRO: Update to ScummVM 2.1.0

### PR DESCRIPTION
**Pull request by RobLoach**
This brings in the latest from v2.1.0 into the libretro core. It's currently missing an update to `LibRetroFilesystemNode`.

## TODO

- [x] Update `backends/fs/libretro/libretro-fs.h` to the new spec
- [x] Update the libretro list of supported engines

@ccawley2011 Would you be willing to update `LibRetroFilesystemNode` to match the new `AbstractFSNode`?

### CODE REVIEW

**Comment by inactive123** [comment]
Looking forward to seeing this PR be completed. It will be awesome getting Blade Runner to finally run on ScummVM.

**Comment by ccawley2011** [comment]
I pushed some changes to [this branch](https://github.com/ccawley2011/scummvm/tree/update-2.1.0). Does this work for you?

**Comment by Darknior** [comment]
WOAW yes incredible, i really wish the LR ScummVM progress and become a real alternative to use on many devices :)

**Comment by RobLoach** [comment]
@ccawley2011  Thank you so much for the help! Tested this out, and was able to run monkey2 without any issues.

Screenshot at 2019-11-03 04-21-21

**Comment by Darknior** [comment]
You really make a fantastic work !!!
Really <3
@RobLoach will you also try to move or copy some ScummVM option to the LR CORE menu to make them easy to use and save like all other core ?
Thanks

**Comment by RobLoach** [comment]
Made https://github.com/libretro/scummvm/issues/151 as a follow up issue. Great idea.

**Comment by hizzlekizzle** [comment]
@RobLoach is this one ready to merge?

**Comment by RobLoach** [comment]
@hizzlekizzle This should be good to go, yes. Was able to save and load a game without issue.

**Pull request merged**
