### PR TITLE
[WIP] Update to 1.8.0

### PR DESCRIPTION
**Pull request by RobLoach**
:warning: DO NOT MERGE.

Still running into this error, unrelated to the 1.8.0 update:

```
    C++      backends/fs/posix/posix-fs.o
backends/fs/posix/posix-fs.cpp:35:26: fatal error: retro_dirent.h: No such file or directory
compilation terminated.
Makefile.common:104: recipe for target 'backends/fs/posix/posix-fs.o' failed
```

Likely missing an include path for posix?

### CODE REVIEW

**Comment by inactive123** [comment]
It works for me here. Does the include path point to libretro-common's include dir?

**Comment by RobLoach** [comment]
@twinaphex Your latest Buildfix commit, along with adding the include directory in `configure` fixed it: https://github.com/libretro/scummvm/pull/29

**Comment by RobLoach** [comment]
Now running into this error:

```
    C++      backends/fs/posix/posix-fs.o
backends/fs/posix/posix-fs.cpp: In function ‘bool Posix::assureDirectoryExists(const Common::String&, const char*)’:
backends/fs/posix/posix-fs.cpp:170:14: error: aggregate ‘Posix::assureDirectoryExists(const Common::String&, const char*)::stat sb’ has incomplete type and cannot be defined
  struct stat sb;
              ^
Makefile.common:104: recipe for target 'backends/fs/posix/posix-fs.o' failed
make: *** [backends/fs/posix/posix-fs.o] Error 1
```

**Comment by inactive123** [comment]
That variable can go, pushed a commit for it.

**Pull request merged**
