### PR TITLE
Disable SWORD25 engine as this does not compile on all platforms.

### PR DESCRIPTION
**Pull request by diablodiab**

### CODE REVIEW

**Comment by Sir-Walrus** [comment]
Nice start, but how about disabling it only on the broken platforms? Or at least add a comment saying which platforms it's broken on?

(Or fix it, but that can take quite a lot of effort.)

**Comment by diablodiab** [comment]
It does not compile on Linux, and judging from the dates of the nightly builds not on OSX either. Not sure about Windows, the buildbot build dates back to december.

**Comment by diablodiab** [comment]
Anyway, found the problem. That specific engine requires that ZLIB is enabled when you compile the ScummVM core:
DEFINES += -DUSE_ZLIB
LDFLAGS += -lz

I don't know if the buildbot system is able to link to zlib, so my guess is that it is better to disable the engine for now. A better long term fix might be to include zlib in the sources for the Scummvm core and compile it into the core instead of linking it. I'm not sure how your policy is about this.

**Comment by Sir-Walrus** [comment]
Linking zlib sounds perfectly fine to me. -lz is better than broken core.

But yeah, we usually embed zlib when required. We do in RetroArch, at least.

(hi twinaphex, as merge-happy as always I see)

**Comment by diablodiab** [comment]
If linking external libraries is acceptable, then I can submit a fix for:
https://github.com/libretro/scummvm/issues/12

To get vorbis support working on ScummVM it is necessary to link to vorbis and ogg libraries.

On Android vorbis is replaced by tremor - I can incorporate tremor into the ScummVM source. I have this working on my Android units.

**Pull request merged**
