### PR TITLE
Add Vorbis and compressed files support to Android version

### PR DESCRIPTION
**Pull request by diablodiab**
Adds Tremor library to libretro-common and updates Makefile to build for android-armv7 with Vorbis (using Tremor) and Zip-support. This enables ScummVM on Android to play back audio and video files compressed with ScummVM tools.

Tested on Nvidia Shield and Huawei Honor 7.

### CODE REVIEW

**Comment by inactive123** [comment]
Im fine with baking tremor inside the scummvm core but it shouldnt be incorporated into libretro-common. Move it to some subdir inside backends/platform/libretro instead.

**Comment by diablodiab** [comment]
libretro-common is also inside backends/platform/libretro

But I can place it in its own directory in backends/platform/libretro next to libretro-common. You still want it moved?

**Comment by inactive123** [comment]
Yes I want it moved. libretro-common will never become a kitchensink of dependencies.

**Comment by diablodiab** [comment]
Ok good, I'll update it tonight.

**Pull request closed without merging**
